/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * IoT Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */


/**
 * Used to indicate an error occurred in generic processing.
 * <p>
 * @author Harbormaster Dev Team
 */

namespace iotonaspdotnet.Exceptions
{
    /// <summary>
    /// Common  exception thrown during the processing a business request
    /// </summary>
	public class ProcessingException: System.Exception
	{
        /// <summary>
        /// sole constructor
        /// </summary>
        /// <param name="message"></param>
   		public ProcessingException(string message): base(message)
   		{
   		}
	}
}

